In [16]:
import numpy as np

n_array = np.array([[1,2,4],[4,3,7]])
print(n_array.ndim)
print(n_array.dtype.name)
print(n_array.shape)
print(n_array.size)

2
int32
(2, 3)
6


In [27]:
a = np.array([1,2,3,4])
b = np.array([0,1,2,3])
c = a- b
d = a + b
e = b*b
#trigonometricc functions can also be applied to the elements of the array
g = np.cos(a)
#conditional operators
print(b<2)
print(c)
print(d)
print(b)
print(e)
print(g)

[ True  True  True False]
[1 1 1 1]
[1 3 5 7]
[0 1 2 3]
[0 1 4 9]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


In [29]:
a1 = np.array([[1,2],[1,1]])
b1 = np.array([[3,5],[4,6]])
c = a1*b1
#dot product
d = np.dot(a1,b1)
print(c)
print(d)

[[ 3 10]
 [ 4  6]]
[[11 17]
 [ 7 11]]


In [51]:
#aa = np.array([1,2,3,4,5])
print(n_array[0])
print(n_array[0:3]) #selects the first three value of the first row
print(n_array[1,:])
print(n_array[:,2])

[1 2 4]
[[1 2 4]
 [4 3 7]]
[4 3 7]
[4 7]


In [56]:
#Shape manipulation of the array
arr = np.ravel(n_array)
print(arr)
arr.shape = (3,2)
print(arr)
barr = arr.transpose()
print(barr)

[1 2 4 4 3 7]
[[1 2]
 [4 4]
 [3 7]]
[[1 4 3]
 [2 4 7]]
